language: haskell
ghc: 7.8
branches:
  only:
  - master
#before install:
#- git submodule foreach --recursive 'git checkout master; git ls-files | grep -v README | grep -v CNAME | xargs -r git rm'
before_script:
- git config --global user.email "$GIT_EMAIL"
- git config --global user.name "$GIT_NAME"
after_script:
- cd _site
- export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
- git remote add upstream "https://$GH_TOKEN@$REMOTE"
- git fetch upstream
- git reset upstream/gh-pages
- git add --all .
- git status
- git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )"
- git push upstream HEAD:gh-pages
env:
  global:
    - secure: "g2McsVAO/2/kXTiXphNdyI/Yt57RES4Tn5Nmu1yhWoZtIuOB86doFC2VKGdfYK3kf3HMsxjgLP8a3S4TeTQ8T6NJCioYBFdVd3K7WC+v05NgkF+8t4p+DypRDkEfvk2URHw+vWrOo6YQrfMPmeRlQYCpAahRqIMcz5QQO8Nfgv6gGyxDDHyOqB0is8UflIP0RgFcUhKo+P99vcLNzzfoFNs+6hjf8Mdgiy10Z7rOLjDknTq0JUlyy+oZumWqd0XGSMn5dydGfFRccA1tYAheWWEx9IpR8AP+rwp337vBBBvT2t4JD4o535GSD+3Mxr5zacc9saae+FCM0D2dtgBOdePiWv60LE8BQHTsyO5BYZc82baQX187AtQ+24EtY7R0Eku35LatQtr4GCEI2wGEqpNEAjYyy+b3pXZDoaZpFWkFPbGHIdVng5C3mZLSaWIBjVzOwGNP7MlPvsjFA1wfy+Zh3J9n+knZTS5WO6T6fHNiFB1sNRzyS3CZ9NVzCLWICRdWbCvAo1iINhtvbdzy7ZouuMk9s6gwtexz8k93k+tfHCqCFOz5R0FnvQoHLuzQ4BgjTQdrjktICuDjGSqq/q5lAv2wCp/7xG7GKaYw1L40oVm/InVbRhi2IIU8jWfj5gXxTQ6sQ39qb4DeXkuKvSUaBq/WpYREaHunAguo6M8="
# end
